# oracle 1521
# mysql & mariadb 3306
# sql server 1433
# postgresql 5432
# db2 50000
# h2 9092
spring:
  application:
    name: pcmspringboot31
  datasource:
#    url: jdbc:sqlserver://localhost;databaseName=BEB31;schema=projectz;trustServerCertificate=true
    url: e84b3efac0261a03fff0c5182c725421fca147c61a2530b148ed6cbcabf727df4c99eb129046ef3ec6d7d3eafdfb47413abcc8cd85318145d99908aafe7f4b0db594c3a51aa6675b6af17f83ba3b3d59bace672d05bd6d91a2ac30bf56bab411
#    url: jdbc:mariadb://localhost:3309/beb31?useSSL=false&serverTimezone=UTC
    username: 6d4bbf96fec4cbd55fc9be6954a06d17
    password: 034456e6b2b6e4a86a38ffc10fbe7445
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
#    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
      dialect: org.hibernate.dialect.SQLServerDialect
#      dialect: org.hibernate.dialect.MariaDBDialect
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        default_schema: projectz
cumi:
    api:
        base-url: http://localhost:8080/api
    es:
        asal-asalan:
            - index1
            - index2
#cumi.api.base-url
#cumi.es.defined-indexes